---
# AutoClearLagg (ACL) Settings #

# seconds between each clear lagg #
seconds: 300

# things to clear #
items: true
mobs: true

# messages sent to everyone on server #
time-left-message: clear lagg in {SECONDS} seconds
items-cleared-message: cleared {COUNT} items
mobs-cleared-message: cleared {COUNT} mobs

# display seconds when lagg will clear #
times: [60, 30, 15, 10, 5, 4, 3, 2, 1]
...
